"""a

Revision ID: 59fd45e18c37
Revises: 74b41f7f738d
Create Date: 2023-08-31 13:31:54.749116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fd45e18c37'
down_revision: Union[str, None] = '74b41f7f738d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followings', sa.Column('users', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('reposts', sa.Column('users', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reposts', 'users')
    op.drop_column('followings', 'users')
    # ### end Alembic commands ###
