"""a

Revision ID: 74b41f7f738d
Revises: 5c74811a0feb
Create Date: 2023-08-31 13:31:25.552363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74b41f7f738d'
down_revision: Union[str, None] = '5c74811a0feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followings', 'users')
    op.drop_column('reposts', 'users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reposts', sa.Column('users', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('followings', sa.Column('users', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
